---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: testuserplane
  namespace: openshift-argocd
spec:
  config: '{ "cniVersion": "0.3.1", "name": "testuplane", "type": "ipvlan", "master": "ens3", "mode": "l2", "ipam": {"type": "static","addresses": [{"address": "10.253.17.73/16"}] } }'

--- 

